networks:
  default:
    name: opentelemetry-demo
    driver: bridge
services:

  jaeger:
    image: "jaegertracing/all-in-one:1.54"
    container_name: "jaeger"
    environment:
      - SPLUNK_USER=admin
      - SPLUNK_PASSWORD=admin123
      - SPLUNK_SERVICE_URL=https://splunk:8089/servicesNS/-/pointertrace/jaeger-api
    ports:
      - "80:80"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"