#networks:
#  default:
#    name: opentelemetry-demo
#    driver: bridge
services:

  first-jaeger:
    image: "jaegertracing/all-in-one:1.54"
    container_name: "first-jaeger"
#    environment:
#      - COLLECTOR_OTLP_GRPC_HOST_PORT=0.0.0.0:4444
#      - COLLECTOR_UI_BIND_HOST_PORT=0.0.0.0:16687
#      - QUERY_HTTP_SERVER_HOST_PORT=0.0.0.0:16687
    ports:
      - "16687:16686"
      - "4444:4317"
  second-jaeger:
    image: "jaegertracing/all-in-one:1.54"
    container_name: "second-jaeger"
    ports:
      - "16686:16686"
      - "4317:4317"
