receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8880"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
