receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8080"
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

service:
  telemetry:
    metrics:
      level: none
#      address: "0.0.0.0:8080"
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      exporters: [jaeger]
