siglets:
  - name: springboot-metric-from-span-spanlet-example
    siglet-class: io.github.pointertrace.siglet.container.example.bundle.springboot.metricfromspan.siglet.MetricFromSpanSpanlet
    checker-factory-class: io.github.pointertrace.siglet.container.example.bundle.springboot.metricfromspan.parser.MetricFromSpanConfigChecker
    description:  generate metrics from spans