global:
  internal-metrics-endpoint-url: http://localhost:4318/v1/metrics
  internal-metrics-export-interval-millis: 1000
receivers:
  - grpc: receiver
    config:
      address: 0.0.0.0:8081
      max-inbound-message-size-bytes: 33554432
      flow-control-window-bytes: 16777216
      max-concurrent-calls-per-connection: 4096
      keep-alive-time-seconds: 5
      permit-keep-alive-time-seconds: 1
exporters:
  - grpc: exporter
    config:
      address: 0.0.0.0:8082
pipelines:
  - name: pipeline
    from: receiver
    start: suffix-spanlet
    processors:
      - fatjar-suffix-spanlet-example: suffix-spanlet
        to: exporter
        config:
          suffix: -added-suffix
