receivers:
  - grpc: receiver
    config:
      address: 0.0.0.0:8081
exporters:
  - grpc: exporter
    config:
      address: otel-lgtm:4317
pipelines:
  - name: pipeline
    from: receiver
    start: suffix-spanlet
    processors:
      - spanlet-groovy-action: suffix-spanlet
        to: exporter
        thread-pool-size: 1
        config:
          action: |
            send {
              newGauge {
                name "span_duration_groovy"
                description "span duration from groovy"
                unit "nanoseconds"
                dataPoint {
                    value  signal.endTimeUnixNano - signal.startTimeUnixNano
                    timeUnixNano signal.startTimeUnixNano
                    attributes {
                      "span-name" signal.name
                    }
                }
              }
            } to "exporter"
