siglets:
  - name: springboot-suffix-spanlet
    siglet-class: io.github.pointertrace.siglet.impl.test.bundle.springboot.suffix.siglet.SuffixSpanlet
    checker-factory-class: io.github.pointertrace.siglet.impl.test.bundle.springboot.suffix.parser.SuffixConfigChecker
    description: adds a suffix to span name