siglets:
  - name: springboot-suffix-spanlet
    siglet-class: io.github.pointertrace.siglet.impl.test.bundle.springboot.suffix.siglet.SuffixSpanlet
    config-factory-class: io.github.pointertrace.siglet.impl.test.bundle.springboot.suffix.config.SuffixConfigFactory
    description: adds a suffix to span name