siglets:
  - name: springboot-suffix-spanlet-example
    siglet-class: io.github.pointertrace.siglet.container.example.bundle.springboot.suffix.siglet.SuffixSpanlet
    checker-factory-class: io.github.pointertrace.siglet.container.example.bundle.springboot.suffix.parser.SuffixConfigChecker
    description: adds a suffix to span name