siglets:
  - name: fatjar-suffix-spanlet
    siglet-class: io.github.pointertrace.siglet.impl.test.bundle.jatjar.suffix.siglet.SuffixSpanlet
    config-parser-factory-class: io.github.pointertrace.siglet.impl.test.bundle.jatjar.suffix.config.SuffixConfigParserFactory
    description: adds a suffix to span name