<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.pointertrace.siglet</groupId>
        <artifactId>siglet-parent</artifactId>
        <version>0.0.13</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>io.github.pointertrace.siglet.api</groupId>
    <artifactId>siglet-api</artifactId>
    <packaging>jar</packaging>
    <name>Siglet API</name>
    <description>API to implement siglets</description>

    <properties>
        <java.version>8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.github.pointertrace.siglet.parser</groupId>
            <artifactId>siglet-yaml-parser</artifactId>
            <version>0.0.5</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
